namespace AutoDealerPro.Modules.Leads.Core.Entities
{
    public class FollowUp
    {
        public Guid Id { get; set; }
        public Guid LeadId { get; set; }
        public string Notes { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? NextFollowUpDate { get; set; }

        private FollowUp() { }

        public static FollowUp Create(string notes, DateTime? nextFollowUpDate = null)
        {

            ValidateNotes(notes);

            return new FollowUp
            {
                //do not create Id here, it will be generated by the database
                Notes = notes,
                CreatedAt = DateTime.UtcNow,
                NextFollowUpDate = nextFollowUpDate
            };
        }
        private static void ValidateNotes(string notes)
        {
            if (notes.Length > 500)
                throw new ArgumentException("Follow-up notes cannot exceed 500 characters", nameof(notes));
        }
    }
}
